version: '3.8'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - ./.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    restart: always
    image: "postgres"
    ports:
      - "6500:5432"
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-db: